# Espacios vectoriales 

En este documento ilustraremos cómo usar `R` para resolver los problemas tipo propuestos por L. Merino y E. Santos en  [página de resolución de ejercicios tipo](https://www.ugr.es/~lmerino/ALME.html) correspondientes al bloque "Espacios Vectoriales".

## Coordenadas. Dependencia lineal

### Ejercicio

*Se considera en el espacio vectorial ${\mathbb{R}}^3$ la base $B=\{(1,0,1), (0,2,0) , (0,0,3)\}$. Determinar el vector $x$ 
cuyas cordenadas respecto de $B$ son $x=(2,1,2)_{B}$.*

Nuestro vector tiene coordenadas $(2,1,2)_B$, por lo que $x=2\times(1,0,1)+1\times(0,2,0)+2\times (0,0,3)$. Ponemos por tanto los vectores de $B$ como columnas en un matriz y multiplicamos por el vector $(2,1,2)$.

In [1]:
B<-cbind(c(1,0,1),c(0,2,0),c(0,0,3))
B

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 1    0    3

In [2]:
B%*%c(2,1,2)

[,1]
[1,] 2   
[2,] 2   
[3,] 8

Con lo que nuestro vector es $(2,2,8)$.

### Ejercicio

*Se considera en el espacio vectorial ${\mathbb{R}}^3$ la base $B=\{(1,0,1), (0,2,0) , (0,0,3)\}$. Determinar 
coordenadas respecto de $B'$ del vector $x=(5,4,2)$.*

Tenemos que encontrar $a,b,c\in \mathbb{R}$ tales que $(5,4,2)=a(1,0,1)+b(0,2,0)+c(0,0,3)$, y esto equivale a resolver el sistema 

$$
\left\{
\begin{array}{rcl}
a&=&5,\\
2b&=&4,\\
a+3c&=&2.
\end{array}
\right.
$$

Aprovechamos que ya tenemos definida la matriz $B$ del ejercicio anterior.

In [3]:
B<-cbind(c(1,0,1),c(0,2,0),c(0,0,3))
solve(B,c(5,4,2))

[1]  5  2 -1

Por lo que $x=(5,3,-1)_B$.

### Ejercicio

*En el espacio vectorial $\mathcal{P}_3(\mathbb{R})$ se consideran los vectores $p(x) = x^3+x^2+x+1$, $q(x)= 2x^2+1$ y $r(x)= x^3+2x^2$. Estudiar si son linealmente dependientes o independientes.*

Consideramos la base estándar de $\mathcal{P}_3(\mathbb{R})$, $B=\{1,x,x^2, x^3 \}$. Respecto de esta base, las coordenadas de los vectores que nos dan son:
$$ p(x)=(1,1,1,1)_B, \;\; q(x)=(1,0,2,0)_B, \;\; r(x)=(0,0,2,1)_B. $$
De esta forma, si ponemos esos vectores en una matriz y vemos su forma reducida por filas, podremos ver si son linealmente dependientes o no. Para ello haremos uso de `rref` del paquete [pracma](https://cran.r-project.org/package=pracma).

In [4]:
A<-rbind(c(1,1,1,1),c(1,0,2,0),c(0,0,2,1))

In [5]:
library("pracma")
rref(A)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    -1.0
[2,] 0    1    0     1.5
[3,] 0    0    1     0.5

Vemos que la matriz tiene rango máximo, por lo que los vectores del enunciado son linealmente independientes.

### Ejercicio
*En el espacio vectorial ${\mathfrak M}_2(\mathbb{R})$ se consideran los vectores  $a=\begin{pmatrix} 1  & 2 \\ 2 & 1 \end{pmatrix}$,  $b=\begin{pmatrix} 1  & 1 \\ 2 & 0 \end{pmatrix}$,  $c=\begin{pmatrix} 0  & 1 \\ 2 & 1 \end{pmatrix}$ y   $b=\begin{pmatrix} 1  & 2 \\ 3 & 1 \end{pmatrix}$.    Estudiar si son linealmente dependientes o independientes.*

Consideramos la base estándar de ${\mathfrak M}_2(\mathbb{R})$, $B=\left\{
 \begin{pmatrix} 1  & 0 \\ 0 & 0 \end{pmatrix},
 \begin{pmatrix} 0  & 1 \\ 0 & 0 \end{pmatrix},
 \begin{pmatrix} 0  & 0 \\ 1 & 0 \end{pmatrix},
 \begin{pmatrix} 0  & 0 \\ 0 & 1 \end{pmatrix}
 \right\}$.
Respecto de esta base los vectores dados tienen coordenadas $(1,2,2,1)_B$, $(1,1,2,0)_B$, $(0,1,2,1)_B$ y $(1,2,3,1)_B$, respectivamente. Procedemos como antes poniendo esos vectores por filas en una matriz y calculamos su forma reducida por filas.

In [6]:
A<-rbind(c(1,2,2,1),c(1,1,2,0),c(0,1,2,1),c(1,2,3,1))
rref(A)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    -1  
[2,] 0    1    0     1  
[3,] 0    0    1     0  
[4,] 0    0    0     0

Como podemos observar, hay una fila de ceros, por lo que a lo sumo tres de ellos son linealmente independientes, y los cuatro son linealmente dependientes.

In [10]:
AI<-cbind(A,diag(4))
AIr<-rref(AI)
AIr

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    0    0    -1   0     1   -1    0  
[2,] 0    1    0     1   0    -2   -1    2  
[3,] 0    0    1     0   0     1    1   -1  
[4,] 0    0    0     0   1     1    1   -2

In [13]:
Q<-AIr[,5:8]
Q

[,1] [,2] [,3] [,4]
[1,] 0     1   -1    0  
[2,] 0    -2   -1    2  
[3,] 0     1    1   -1  
[4,] 1     1    1   -2

In [14]:
Q%*%A

[,1] [,2] [,3] [,4]
[1,] 1    0    0    -1  
[2,] 0    1    0     1  
[3,] 0    0    1     0  
[4,] 0    0    0     0

Al ser la última fila todo ceros, ya tenemos la relación de dependencia lineal.

In [15]:
c(1,1,1,-2)%*%A

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0

Por lo que $a+b+c-2d=0$.

## Cambio de base

### Ejercicio

*En el espacio vectorial $\mathcal{P}_3(\mathbb{R})$ de los polinomios de grado menor o igual que $3$, se consideran las bases estándar $B=\{1,x,x^2, x^3 \}$ y $B'=\{x^3+x^2+x+1, x^3+x^2+x, x^3+x^2, x^3\}$. Determinar la ecuación del cambio de base de $B$ a $B'$ y las coordenadas respecto de $B'$ del vector $p(x)=x^3+2x$.*

Tenemos que los vectores de $B'$ tienen coordenadas
$$
\begin{array}{lcl}
x^3+x^2+x+1 &= & (1,1,1,1)_B, \\
x^3+x^2+x   &= & (0,1,1,1)_B, \\
x^3+x^2     &= & (0,0,1,1)_B, \\
x^3         &= & (0,0,0,1)_B.
\end{array}
$$

Por lo que la matriz de cambio de base de $B'$ a $B$ es 
$$
P=
\begin{pmatrix}
1 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 \\
1 & 1 & 1 & 0 \\
1 & 1 & 1 & 1
\end{pmatrix}.
$$
Y la de $B$ a $B'$ será su inversa.

In [16]:
P<-cbind(c(1,1,1,1),c(0,1,1,1),c(0,0,1,1),c(0,0,0,1))
P

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 1    1    0    0   
[3,] 1    1    1    0   
[4,] 1    1    1    1

La inversa la podemos calcular con `pracma::inv` o con `solve`. 

In [17]:
inv(P)

[,1] [,2] [,3] [,4]
[1,]  1    0    0   0   
[2,] -1    1    0   0   
[3,]  0   -1    1   0   
[4,]  0    0   -1   1

In [18]:
solve(P)

[,1] [,2] [,3] [,4]
[1,]  1    0    0   0   
[2,] -1    1    0   0   
[3,]  0   -1    1   0   
[4,]  0    0   -1   1

El polinomio $p(x)$ tiene coordenadas $(0,2,0,1)_B$, por lo que sus coordenadas respecto de $B'$ son

In [19]:
inv(P)%*%c(0,2,0,1)

[,1]
[1,]  0  
[2,]  2  
[3,] -2  
[4,]  1

esto es, $p(x)=(0,2,-2,1)_{B'}$

### Ejercicio

*En el espacio vectorial $\mathbb{R}^3$ se consideran las bases $B'=\{ (1,1,0), (0,1,2),  (1,0,1) \}$   y  $B''=\{(1,0,0), (2,1,0), (1,1,1)\}$. Determinar la ecuación del cambio de base de $B'$ a $B''$.*

Vamos a determinar la matriz de cambio de base $P$ de $B'$ a la base estándar $B$, y luego la de $B$ a $B''$, $Q$. Multiplicando $Q$ y $P$, tendremos la matriz de cambio de base de $B'$ a $B''$.

In [20]:
P<-cbind(c(1,1,0),c(0,1,2),c(1,0,1))
Q<-inv(cbind(c(1,0,0),c(2,1,0),c(1,1,1)))

In [24]:
P

[,1] [,2] [,3]
[1,] 1    0    1   
[2,] 1    1    0   
[3,] 0    2    1

In [21]:
Q

[,1] [,2] [,3]
[1,] 1    -2    1  
[2,] 0     1   -1  
[3,] 0     0    1

In [23]:
Q%*%P

[,1] [,2] [,3]
[1,] -1    0    2  
[2,]  1   -1   -1  
[3,]  0    2    1

## Espresiones de un subespacio

### Ejercicio

*En el espacio vectorial $\mathcal{P}_3(\mathbb{K})$ de los polinomios de grado menor o igual que $3$, se considera el subespacio $U$ generado por $2x^3+2x+1, 2x^3+x^2+3x+1, x^3+x^2+2x, 2x^2+2x+1$. Determinar una base de $U$, unas ecuaciones paramétricas y unas cartesianas.*

Consideramos la base estándar $B=\{1,x,x^2,x^3\}$ de $\mathcal{P}_3(\mathbb{K})$, entonces
$$
\begin{array}{rcl}
 2x^3+2x+1    & = & (1,2,0,2)_B, \\
2x^3+x^2+3x+1 & = & (1,3,1,2)_B, \\
x^3+x^2+2x    & = & (0,2,1,1)_B, \\
2x^2+2x+1     & = & (1,2,2,0)_B.
\end{array}
$$
Para encontrar una base, calculamos la forma normal reducida de la matriz cuyas filas son esas coordenadas.

In [25]:
A<-rbind(c(1,2,0,2),c(1,3,1,2),c(0,2,1,1),c(1,2,2,0))

In [28]:
rA<-rref(A)
rA

[,1] [,2] [,3] [,4]
[1,] 1    0    0     0  
[2,] 0    1    0     1  
[3,] 0    0    1    -1  
[4,] 0    0    0     0

Por lo que una base de $U$ es $\{(1,0,0,0),(0,1,0,1),(0,0,1,-1)\}$. Las ecuaciones paramétricas serán
$$
\left\{ \begin{array}{rcl}
x_1 &=& \lambda,     \\
x_2 &=& \mu,  \\
x_3 &=& \gamma, \\
x_4  &=&  \mu - \gamma.
\end{array} \right.
$$

Para encontrar las ecuaciones implícitas, vamos a colocar los vectores de la base que hemos elegido de $U$ por columnas.

In [30]:
U<-t(rA[1:3,])
U

[,1] [,2] [,3]
[1,] 1    0     0  
[2,] 0    1     0  
[3,] 0    0     1  
[4,] 0    1    -1

Le añadimos la identidad.

In [57]:
cbind(U,diag(4))

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0     0   1    0    0    0   
[2,] 0    1     0   0    1    0    0   
[3,] 0    0     1   0    0    1    0   
[4,] 0    1    -1   0    0    0    1

Eliminar parámetros (tres primeras columnas) se corresponde con encontrar la forma reducida por filas, y ver en qué filas dejan de haber parámetros.

In [31]:
rref(cbind(U,diag(4)))

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0    0    1    0     0    0  
[2,] 0    1    0    0    0     1    1  
[3,] 0    0    1    0    0     1    0  
[4,] 0    0    0    0    1    -1   -1

De la última fila se deduce que una ecuación implícita de $U$ es $x_2-x_3-x_4=0$.

### Ejercicio

*En $\mathfrak{M}_2(\mathbb{R})$ se considera el subespacio $U$ que tiene ecuaciones cartesianas respecto de la base estándar*
$$
\left\{ \begin{array}{rcl}
x+y+t&=& 0, \\
2x-y+t&=& 0.
\end{array} \right.
$$
*Determinar una base de $U$.*

In [35]:
A<-rbind(c(1,1,0,1),c(2,-1,0,1))
Ab<-cbind(A,c(0,0))
Ab

[,1] [,2] [,3] [,4] [,5]
[1,] 1     1   0    1    0   
[2,] 2    -1   0    1    0

In [36]:
rref(Ab)

[,1] [,2] [,3] [,4]      [,5]
[1,] 1    0    0    0.6666667 0   
[2,] 0    1    0    0.3333333 0

Por lo que nuestro sistema original es equivalente a
$$
\left\{ \begin{array}{rcl}
x+\frac{2}{3} t&=& 0, \\
y+\frac{1}{3}t&=& 0. 
\end{array} \right.
$$

Tomando como parámetros $z$ y $t$, y pasando a paramétricas obtenemos que una base de $U$ es $\{(0,0,1,0)_B, (-2/3,-1/3,0,1)_B\}$, esto es, 
$$
\left\{\begin{pmatrix}
-\frac{2}{3} & -\frac{1}{3} \\
0 & 1
\end{pmatrix}
,
\;
\begin{pmatrix}
0 & 0 \\
1 & 0
\end{pmatrix}
\right\}.
$$ 

Esto también lo podemos obtener calculando la forma reducida por filas de la traspuesta de $A$. 

In [46]:
rtAI<-rref(cbind(t(A),diag(4)))
rtAI

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0     0.5 0     0.5
[2,] 0    1    0    -0.5 0     0.5
[3,] 0    0    1     0.5 0    -1.5
[4,] 0    0    0     0.0 1     0.0

La matriz de paso es 

In [51]:
Q<-rtAI[,-(1:2)]
Q

[,1] [,2] [,3] [,4]
[1,] 0     0.5 0     0.5
[2,] 0    -0.5 0     0.5
[3,] 1     0.5 0    -1.5
[4,] 0     0.0 1     0.0

Al ser las dos últimas filas de la forma reducida de `t(A)` cero, esto nos dice que las dos últimas filas de $Q$ son una base para $U$, pues son linealmente independientes y verifican las ecuaciones de $U$.

In [56]:
Q[3:4,]

[,1] [,2] [,3] [,4]
[1,] 1    0.5  0    -1.5
[2,] 0    0.0  1     0.0

Lo que nos dice que otra posible base es $\{(0,0,1,0)_B,(1,1/2,0,-3/2)_B\}$ (nótese que el último vector es $-2/3$ por el segundo vector que obtuvimos antes).

## Paso de generadores a implícitas y viceversa

Vamos a escribir una función que nos permita calcular las ecuaciones implícitas de un subespacio vectorial a partir de un sistema de generadores de dicho subespacio, y viceversa. 

Supongamos que nuestro subespacio vectorial $U\subseteq \mathbb{R}^n$ está generado por $\{v_1,\dots,v_k\}$. Supongamos que la dimensión de $U$ es $d$, que además coincide con el rango de la matriz $A$ cuyas columnas son $v_1,\dots, v_k$. Supongamos que $H$ es la forma normal reducida por columnas de $A$, y que $Q$ es tal que $Q A=H$. Tenemos entonces que las últimas $n-d$ columnas de $H$ son cero. Esto quiere decir que las últimas $d-n$ filas de $Q$ cuando las multiplicamos por $A$ dan cero, o dicho de otra forma, esas últimas $d-n$ filas son los coeficientes de ecuaciones que verifican todos los generadores de $U$, y por tanto son unas ecuaciones implícitas de $U$.

Si, en lugar de generadores, partimos de $k$ ecuaciones implícitas de $U$, el proceso es dual, por lo que si en $A$ almacenamos los coeficientes de dichas ecuaciones y tomamos su transpuesta, podemos calcular nuevamente la forma normal de hermite de $A^t$, $H$, y $Q$ tal que $QA^t=H$. Si de esas $k$ ecuaciones, $d$ de ellas son independientes, entonces las últimas $n-d$ columnas de $H$ serán nulas. De esta forma las últimas $n-d$ filas de $Q$ conforman una base de $U$.

Escribamos este proceso en `R`.

In [9]:
library("pracma")
gensec<-function(A){
    # A es una matrix con los generadores del subespacio
    # (o los coeficientes de las ecuaciones que lo definen)                                       
    c<-ncol(A) # número columnas de A                                                                           
    f<-nrow(A) # número de filas de A                                                                           
    r<-Rank(A) # rango de A                                                                                     
    rtAI<-rref(cbind(t(A),diag(c))) # trasponemos A y le añadimos la identidad por columnas                     
    ecs<-rtAI[(r+1):c,(f+1):(f+c)] # nos quedamos con la parte de ceros que corresponden
                                   # a las ecuaciones (o a los generadores dependiendo de la entrada)       
    return(ecs)
}

Veamos su son los dos ejemplos de antes.

### Ejemplo 1

Sea $U=\mathcal{L}(\{(1,2,0,2),(1,3,1,2),(0,2,1,1),(1,2,2,0) \})\subseteq\mathbb{R}^4$. Calculemos sus ecuaciones implícitas.

In [7]:
A<-rbind(c(1,2,0,2),c(1,3,1,2),c(0,2,1,1),c(1,2,2,0))
A

[,1] [,2] [,3] [,4]
[1,] 1    2    0    2   
[2,] 1    3    1    2   
[3,] 0    2    1    1   
[4,] 1    2    2    0

In [10]:
gensec(A)

[1]  0  1 -1 -1

Por lo tanto la ecuación de $U$ es $x_2-x_3-x_4=0$.


### Ejemplo 2

Sea ahora el subespacio vectorial de $\mathbbR}^4$ con ecuaciones $x_1+x_2+x_4=0$, $2x_1-x_2+x_4=0$.

In [11]:
B<-rbind(c(1,1,0,1),c(2,-1,0,1))
gensec(B)

[,1] [,2] [,3] [,4]
[1,] 1    0.5  0    -1.5
[2,] 0    0.0  1     0.0

Por lo que nuestro subespacio es $\mathcal{L}(\{(1,1/2,0,-3/2),(0,0,1,0)\})$.

## Suma e intersección de subespacios

### Ejercicio

*Determinar bases de la suma y la intersección de los subespacios $U=\mathcal{L}((1,1,0,0), (0,0,1,1))$ y $W=\mathcal{L}((1,1,1,0), (1,1,1,1))$ de $\mathbb{R}^4$.*

Para calcular la suma, basta con calcular una base del espacio vectorial generado por la unión de los generadores de $U$ y $V$.

In [13]:
U<-rbind(c(1,1,0,0),c(0,0,1,1))
V<-rbind(c(1,1,1,0),c(1,1,1,1))
rref(rbind(U,V))

[,1] [,2] [,3] [,4]
[1,] 1    1    0    0   
[2,] 0    0    1    0   
[3,] 0    0    0    1   
[4,] 0    0    0    0

Luego la suma está generada por $\{(1,1,0,0),(0,0,1,0),(0,0,0,1)\}$.

Para la intersección, calculamos las ecuaciones implícitas de $U$ y $V$, y luego las juntamos.

In [20]:
ecU<-gensec(U)
ecU

[,1] [,2] [,3] [,4]
[1,] 1    -1   0     0  
[2,] 0     0   1    -1

Las ecuaciones de $U$ son $x-y=0$, $z-t=0$.

In [21]:
ecV<-gensec(V)
ecV

[,1] [,2] [,3] [,4]
[1,] 1    0    -1   0   
[2,] 0    1    -1   0

Las de $V$ son $x-z=0$, $y-z=0$. Las de la intersección por tanto se obtienen juntando estas ecuaciones y reduciendo.

In [26]:
eqUiV<-rref(rbind(ecU,ecV))
eqUiV

[,1] [,2] [,3] [,4]
[1,] 1    0    0    -1  
[2,] 0    1    0    -1  
[3,] 0    0    1    -1  
[4,] 0    0    0     0

Por tanto las ecuaciones de la intersección son
$$
\left\{ \begin{array}{rcl}
x - t &=& 0, \\
y - t &=&  0, \\
z - t &=& 0.
\end{array} \right.
$$

Teniendo así que $U\cap V$ está generado por $(1,1,1,1)$.

In [25]:
gensec(rbind(ecU,ecV))

[1] 1 1 1 1

## Suma directa de subespacios

### Ejercicio

*Dado el subespacio $U$ de $\mathbb{R}^4$ de ecuaciones cartesianas*
$$
\left\{ \begin{array}{ccc}
x+y & = & 0, \\
t & = & 0.
\end{array} \right.
$$
*Obtener un subespacio complementario de $U$.*

In [29]:
ecU<-rbind(c(1,1,0,0),c(0,0,0,1))
U<-gensec(ecU)
U

[,1] [,2] [,3] [,4]
[1,] 1    -1   0    0   
[2,] 0     0   1    0

In [30]:
Rank(rbind(U,ecU))

[1] 4

Un complementario es por tanto $\mathcal{L}(\{(1,1,0,0),(0,0,0,1)\})$ (los vectores cuyas coordenadas son los coeficientes de las ecuaciones de $U$).

### Ejercicio

*Se consideran los subespacios de $\mathcal{P}_2(\mathbb{R})$ $U=\mathcal{L}(1+x^2)$ y $W$ con ecuación cartesiana respecto de base estándar $x_1 + x_3= 0$. Comprobar que $\mathcal{P}_2(\mathbb{R})=U\oplus W$ y descomponer el vector $1+3x+3x^2$ como suma de un vector de $U$ y uno de $W$.*

Respecto a la base estándar $B=\{1,x,x^2\}$, $U$ está generado por $(1,0,1)$. Encontremos una base para $W$.

In [31]:
U<-rbind(c(1,0,1))
ecW<-rbind(c(1,0,1))
W<-gensec(ecW)
W

[,1] [,2] [,3]
[1,] 1    0    -1  
[2,] 0    1     0

Como 

In [32]:
Rank(rbind(U,W))

[1] 3

Tenemos que $U+W=\mathcal{P}_2(\mathbb{R})$. Además, como $U$ tiene dimensión uno y $W$ tiene dimensión dos, la intersección debe tener dimensión cero, pues $\dim(U\cap W) = \dim(U) + \dim(W) -\dim(U+W)= 1 +2 -3 =0$. Por tanto, $\mathcal{P}_2(\mathbb{R})=U\oplus W$. Esto también queda claro por el hecho de que la ecuación cartesianda de $W$ tiene como coeficientes el vector que genera a $U$.

El polinomio $1+3x+3x^2$ tiene coordenadas $(1,3,3)$ respecto de la base estándar. Calculemos sus coordenadas respecto de la base formada por la unión de las bases de $U$ y $W$, $B'=\{(1,0,1),(1,0,-1),(0,1,0)\}$.

In [34]:
cb<-t(rbind(U,W))
cb

[,1] [,2] [,3]
[1,] 1     1   0   
[2,] 0     0   1   
[3,] 1    -1   0

In [35]:
solve(cb)

[,1] [,2] [,3]
[1,] 0.5  0     0.5
[2,] 0.5  0    -0.5
[3,] 0.0  1     0.0

In [36]:
solve(cb)%*%c(1,3,3)

[,1]
[1,]  2  
[2,] -1  
[3,]  3

Luego $1+3x+3x^2=(2,-1,3)_{B'}=2(1+x^2)-(1-x^2)+3x$, con $2+2x^2\in U$ y $-1+3x+x^2\in W$.

## Matrix de Gram

### Ejercicio

*En el espacio vectorial $\mathcal{P}_2(\mathbb{K})$ de los polinomios de grado menor o igual que $2$, calcular la matriz de Gram del producto escalar definido por*
$$ \langle p(x),q(x)\rangle = \int_{0}^{1} p(x)q(x)dx $$
*respecto de la base estándar $B=\{1,x,x^2 \}$.*

In [164]:
B<-c(function(x)(1), function(x)(x), function(x)(x^2))

Definimos el producto escalar de dos funciones (cuidado que es necesario `Vectorize')

In [165]:
prod<-function(f,g)(integrate(Vectorize(function(x)(f(x)*g(x))),0,1)$value)

In [166]:
G<-matrix(0,3,3)
for (i in 1:3){
    for (j in 1:3){
        G[i,j]<-prod(B[[i]],B[[j]])
        #G[i,j]<-integrate(Vectorize(function(x)(B[[i]](x)*B[[j]](x))),0,1)$value
    }
}
G

[,1]      [,2]      [,3]     
[1,] 1.0000000 0.5000000 0.3333333
[2,] 0.5000000 0.3333333 0.2500000
[3,] 0.3333333 0.2500000 0.2000000

Si vectorizamos `prod`, podemos calcular la matriz de Gram de una forma más sencilla con `outer`.

In [168]:
prod_v<-Vectorize(prod)

In [169]:
outer(B,B,prod_v)

[,1]      [,2]      [,3]     
[1,] 1.0000000 0.5000000 0.3333333
[2,] 0.5000000 0.3333333 0.2500000
[3,] 0.3333333 0.2500000 0.2000000

### Ejercicio

*Con el producto escalar anterior y los polinomios $p(x)= 1+6x-10x^2$ y $q(x)=1+2x+4x^2$, calcular*
 1. $\langle p(x), q(x) \rangle$,
 2. $|| p(x)||$, $||q(x) ||$,  
 3. *el ángulo que determinan $p(x)$ y $q(x)$.

Podemos usar la matriz de Gram antes calculada

In [170]:
p<-function(x)(1+6*x-10*x^2)
q<-function(x)(1+2*x+4*x^2)

In [171]:
prod(p,q)

[1] -4.440892e-16

O bien usando las coordenadas de $p(x)$ y $q(x)$ en la base estándar.

In [173]:
c(1,6,-10)%*%G%*%c(1,2,4)

[,1]         
[1,] -1.776357e-15

En particular esto implica que son ortogonales (el ángulo que forman es $\pi/2$).

En cuanto a las normas

In [174]:
sqrt(c(1,6,-10)%*%G%*%c(1,6,-10))

[,1]    
[1,] 1.527525

In [175]:
sqrt(c(1,2,4)%*%G%*%c(1,2,4))

[,1]    
[1,] 3.768289

## Cálculo de una base ortogonal usando el método de Gram-Schmidt

### Ejercicio

*En $\mathbb{R}^3$ con el producto escalar usual, calcular una base ortogonal a partir de los vectores $\{u_1=(1,1,-1), u_2=(1,-1,1),u_3=(-1,1,1) \}$.*

Vamos a automatizar el proceso del cálculo de los coeficientes $\lambda_{ij}$. Cuardamos los elementos de la base en las filas de una matriz a la que llamamos $U$.

In [230]:
U <- rbind(c(1,1,-1),c(1,-1,1),c(-1,1,1))
m <- nrow(U)
n <- ncol(U)
E <- matrix(0,m,n)

E[1,]<-U[1,]
for(j in 2:n){
    lambda <- numeric(j-1) # inicializamos lambda a cero
    for(i in 1:(j-1)){ # calculamos los valores de los coeficientes correctores
        lambda[i]<- -(U[j,]%*%E[i,])/(E[i,]%*%E[i,]) 
    }
    E[j,] = U[j,]+ lambda%*%E[1:(j-1),] # calculamos el nuevo elemento de la base
}

In [231]:
E

[,1]          [,2]       [,3]      
[1,]  1.000000e+00  1.0000000 -1.0000000
[2,]  1.333333e+00 -0.6666667  0.6666667
[3,] -2.220446e-16  1.0000000  1.0000000

In [232]:
print(fractional(E))

     [,1] [,2] [,3]
[1,]    1    1   -1
[2,]  4/3 -2/3  2/3
[3,]    .    1    1


### Ejercicio

*En $\mathbb{R}^3$ se considera el producto escalar que, con respecto de la base canónica, viene dado por la matriz de Gram*

$$ G=\begin{pmatrix}
2 & 1 & 1 \\
1 & 2 & 1 \\
1 & 1 & 2
\end{pmatrix}.
$$

*Calcular una base ortogonal a partir de los vectores $\{(1,-1,0),(0,1,1),(0,0,1)\}$.*

In [229]:
G<- rbind(c(2,1,1),c(1,2,1),c(1,1,2))
U <- rbind(c(1,-1,0),c(0,1,1),c(0,0,1))
m <- nrow(U)
n <- ncol(U)
E <- matrix(0,m,n)
lambda = c(0,n,n)

E[1,]<-U[1,]
for(j in 2:n){
    lambda = numeric(j-1) # inicializamos lambda a cero
    for(i in 1:(j-1)){ # calculamos los valores de los coeficientes correctores
        lambda[i]<- -(U[j,]%*%G%*%E[i,])/(E[i,]%*%G%*%E[i,]) 
    }
    E[j,] = U[j,]+ lambda%*%E[1:(j-1),] # calculamos el nuevo elemento de la base
}

In [227]:
E

[,1]       [,2]       [,3]     
[1,]  1.0000000 -1.0000000 0.0000000
[2,]  0.5000000  0.5000000 1.0000000
[3,] -0.2727273 -0.2727273 0.4545455

In [228]:
print(fractional(E))

     [,1]  [,2]  [,3] 
[1,]     1    -1     .
[2,]   1/2   1/2     1
[3,] -3/11 -3/11  5/11
