# Sistemas de ecuaciones, matrices y determinantes

Utilizaremos como ejemplos los proporcionados por L. Merino y E. Santos en su [página de resolución de ejercicios tipo](https://www.ugr.es/~lmerino/ALME.html) de su libro [Álgebra lineal con métodos elementales](https://www.amazon.es/%C3%81lgebra-lineal-m%C3%A9todos-elementales-GONZALEZ/dp/8497324811).

## Forma normal de Hermite de una matriz

Para calcular la forma normal de Hermite por filas, vamos a utilizar el paquete [pracma](https://cran.r-project.org/web/packages/pracma/index.html).

Empezamos comprobando si está disponible y, en caso contrario, lo instalamos.

Esto lo podemos hacer con `if(!require("pracma")) install.packages("pracma")`. Como nosotros ya lo tenemos instalado, simplemente cargamos la librería.

In [1]:
library("pracma")

### Ejercicio

*Calcular la forma de Hermite por filas y el rango de la
matriz:*
$$
A=
 \left(\begin{array}{rrrr}
-2 & -4 &  2  &  2 \\
 3 &  6 &  -3 & -3 \\
 1 &  2 &  0  &  1
 \end{array}\right).
$$

Empezamos definiendo la matriz del enunciado.

In [2]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
A

[,1] [,2] [,3] [,4]
[1,] -2   -4    2    2  
[2,]  3    6   -3   -3  
[3,]  1    2    0    1

Para calcular la forma normal de Hermite por filas, usamos `rref` (row reduced echelon form).

In [3]:
rref(A)

[,1] [,2] [,3] [,4]
[1,] 1    2    0    1   
[2,] 0    0    1    2   
[3,] 0    0    0    0

Y el rango lo podemos calcular con `Rank`.

In [4]:
Rank(A)

[1] 2

### Ejercicio

*Calcular la forma de Hermite por columnas de la matriz*
$$
A= \left(\begin{array}{rrr}
 1 &  2 &  1 \\
 2 &  1 &  0 \\
 4 &  5 &  2 \\
 \end{array}\right).
$$

In [5]:
A<-rbind(c(1,2,1),c(2,1,0),c(4,5,2))
A

[,1] [,2] [,3]
[1,] 1    2    1   
[2,] 2    1    0   
[3,] 4    5    2

Para calcular la forma normal reducida por columnas, calculamos la transpuesta de la forma reducida por filas de la transpuesta de la matriz.

In [6]:
t(rref(t(A)))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 2    1    0

### Ejercicio

*Calcular la forma de Hermite por filas $H$ de la matriz*
$$
A=
 \left(\begin{array}{rrrr}
-2 & -4 &  2  &  2 \\
 3 &  6 &  -3 & -3 \\
 1 &  2 &  0  &  1
 \end{array}\right)
$$
*así como una matriz regular $Q$ de forma que $H=Q\cdot A$*.


Empezamos definiendo la matriz del enunciado, y le añadimos la matriz identidad por columnas.

In [7]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
AI<-cbind(A,diag(3))
AI

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] -2   -4    2    2   1    0    0   
[2,]  3    6   -3   -3   0    1    0   
[3,]  1    2    0    1   0    0    1

Ahora calculamos su forma normal reducida for filas.

In [8]:
hAI<-rref(AI)
hAI

[,1] [,2] [,3] [,4] [,5] [,6]       [,7]
[1,] 1    2    0    1    0     0.0000000 1   
[2,] 0    0    1    2    0    -0.3333333 1   
[3,] 0    0    0    0    1     0.6666667 0

Las primeras cuatro filas nos dan la forma normal reducida por filas.

In [9]:
hAI[,1:4]

[,1] [,2] [,3] [,4]
[1,] 1    2    0    1   
[2,] 0    0    1    2   
[3,] 0    0    0    0

Mientras que las restantes nos dan la matriz de paso.

In [10]:
Q<-hAI[,-(1:4)]
Q

[,1] [,2]       [,3]
[1,] 0     0.0000000 1   
[2,] 0    -0.3333333 1   
[3,] 1     0.6666667 0

Comprobemos que efectivamente $Q A$ es la forma reducida.

In [11]:
Q%*%A

[,1] [,2] [,3] [,4]
[1,] 1    2    0    1   
[2,] 0    0    1    2   
[3,] 0    0    0    0

### Ejercicio

*Calcular la forma de Hermite por columnas $C$ de la matriz*
$$
A=
 \left(\begin{array}{rrrr}
 -2 & -4 &  2 &  2 \\
  3 &  6 & -3 & -3 \\
  1 &  2 &  0 &  1  \\
 \end{array}\right)
$$
*así como una matriz regular $Q$ de forma que $C=A\cdot Q$*.


Procedemos como en el ejercicio anterior, pero ahora añadiendo la identidad por columnas debajo de $A$.

In [12]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
AI<-rbind(A,diag(4))
AI

[,1] [,2] [,3] [,4]
[1,] -2   -4    2    2  
[2,]  3    6   -3   -3  
[3,]  1    2    0    1  
[4,]  1    0    0    0  
[5,]  0    1    0    0  
[6,]  0    0    1    0  
[7,]  0    0    0    1

Calculamos la forma normal de hermite de `AI` por columnas (transponiendo, calculando la forma reducida por filas, y volviendo a transponer).

In [13]:
hAI<-t(rref(t(AI)))
hAI

[,1] [,2] [,3] [,4]
[1,]  1.0  0    0    0  
[2,] -1.5  0    0    0  
[3,]  0.0  1    0    0  
[4,]  0.0  0    1    0  
[5,]  0.0  0    0    1  
[6,]  0.5 -1    2    4  
[7,]  0.0  1   -1   -2

Así la forma reducida por columnas es

In [14]:
hAI[1:3,]

[,1] [,2] [,3] [,4]
[1,]  1.0 0    0    0   
[2,] -1.5 0    0    0   
[3,]  0.0 1    0    0

Y la matriz $Q$ es 

In [15]:
Q<-hAI[-(1:3),]
Q

[,1] [,2] [,3] [,4]
[1,] 0.0   0    1    0  
[2,] 0.0   0    0    1  
[3,] 0.5  -1    2    4  
[4,] 0.0   1   -1   -2

Comprobamos que el resultado es correcto.

In [16]:
all(A%*%Q == hAI[1:3,])

[1] TRUE

## Sistemas de ecuaciones usando Gauss-Jordan

### Ejercicio

*Discutir y resolver, en su caso, el sistema de ecuaciones lineales:*
$$
\left\{ \begin{array}{rcl}
3x +2y +z&= & 1, \\
2x+3y+z &= & 0,\\
2x+ y+3z &= & 0.
\end{array} \right. 
$$

Empezamos definiendo la matriz de coeficientes y la matriz ampliada.

In [17]:
A<- rbind(c(3,2,1),c(2,3,1),c(2,1,3))
b<-c(1,0,0)

Al ser un sistema de ecuaciones con el mismo número de incógnitas que de ecuaciones, podemos utilizar `solve`.

In [18]:
solve(A,b)

[1]  0.6666667 -0.3333333 -0.3333333

Por lo que la solución es $x=2/3$, $y=-1/3$ y $z=-1/3$.

Usando la forma normal reducida de la matriz ampliada

In [19]:
Ab<-cbind(A,b)
Ab

b
[1,] 3 2 1 1
[2,] 2 3 1 0
[3,] 2 1 3 0

In [20]:
rref(Ab)

b         
[1,] 1 0 0  0.6666667
[2,] 0 1 0 -0.3333333
[3,] 0 0 1 -0.3333333

Obtenemos que la solución es única: $x=2/3$, $y=-1/3$ y $z=-1/3$.

En este caso los rangos de la matriz de coeficientes y de la matriz ampliada coinciden y son máximos.

In [21]:
Rank(A)

[1] 3

In [22]:
Rank(Ab)

[1] 3

### Ejercicio

*Discutir y resolver, en su caso, el sistema de ecuaciones lineales:*
$$
\left\{ \begin{array}{rcl}
3x +2y +z&= & 1, \\
2x+3y+z &= & 0,\\
x+ 4y+z &= & 0.
\end{array} \right. 
$$

In [23]:
A<- rbind(c(3,2,1),c(2,3,1),c(1,4,1))
b<-c(1,0,0)

In [24]:
solve(A,b)

ERROR: Error in solve.default(A, b): Lapack routine dgesv: system is exactly singular: U[3,3] = 0


Veamos cómo es la forma reducida por filas de la matriz ampliada.

In [25]:
Ab<- cbind(A,b)

In [26]:
rref(Ab)

b
[1,] 1 0 0.2 0
[2,] 0 1 0.2 0
[3,] 0 0 0.0 1

La incompatibilidad del sistema se aprecia en la última fila, que corresponde a una equación $0=1$.

Podemos ver la incompatibilidad también estudiando los rangos de la matriz de coeficientes y de la ampliada.

In [27]:
Rank(A)

[1] 2

In [28]:
Rank(Ab)

[1] 3

### Ejercicio

*Discutir y resolver, en su caso, el sistema de ecuaciones lineales:*
$$
\left\{ \begin{array}{rcl}
3x +2y +z&= & 1, \\
2x+3y+z &= & 2,\\
x+ 4y+z &= & 3.
\end{array} \right. 
$$

In [29]:
A<- rbind(c(3,2,1),c(2,3,1),c(1,4,1))
b<-c(1,2,3)

In [30]:
solve(A,b)

ERROR: Error in solve.default(A, b): Lapack routine dgesv: system is exactly singular: U[3,3] = 0


El comando `solve` no nos sirve en el caso en que la matriz de coeficientes tenga determinante cero. Veamos qué información podemos sacar de la forma reducida por filas.

In [31]:
Ab<-cbind(A,b)

In [32]:
rref(Ab)

b   
[1,] 1 0 0.2 -0.2
[2,] 0 1 0.2  0.8
[3,] 0 0 0.0  0.0

Por lo que el sistema tiene infinitas soluciones. Podemos tomar $z$ como parámatro. Y las soluciones son $x=-1/5-1/5z$, $y=4/5-1/5z$.

Veamos que en este caso los rangos de la matriz de coeficientes y de la matriz ampliada coinciden, pero no son máximos.

In [33]:
Rank(A)

[1] 2

In [34]:
Rank(Ab)

[1] 2

## Matriz inversa usando operaciones elementales por filas

### Ejercicio

*Estudiar si la matriz*
$$
 \left(\begin{array}{rrrr}
 3 &  2 &  3 & 4 \\
 3 &  2 &  2 &  3 \\
 2 &  1 &  2  & 1 \\
 0 & 1 & 1 & 0
 \end{array}\right)
$$
*es regular y en tal caso, calcular su matriz inversa.*

In [35]:
A<-rbind(c(3,2,3,4),c(3,2,2,3),c(2,1,2,1),c(0,1,1,0))

Si $A$ tiene inversa, la podemos calcular con `solve`.

In [36]:
solve(A)

[,1] [,2]       [,3] [,4]      
[1,] -0.5  0.5000000  0.5 -0.5000000
[2,] -0.5  0.8333333 -0.5  0.8333333
[3,]  0.5 -0.8333333  0.5  0.1666667
[4,]  0.5 -0.1666667 -0.5 -0.1666667

Veamos cómo se puede calcular utilizando la forma normal de Hermite por filas.

In [37]:
AI<-cbind(A,diag(4))

In [38]:
AI

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 3    2    3    4    1    0    0    0   
[2,] 3    2    2    3    0    1    0    0   
[3,] 2    1    2    1    0    0    1    0   
[4,] 0    1    1    0    0    0    0    1

In [39]:
rAI<-rref(AI)
rAI

[,1] [,2] [,3] [,4] [,5] [,6]       [,7] [,8]      
[1,] 1    0    0    0    -0.5  0.5000000  0.5 -0.5000000
[2,] 0    1    0    0    -0.5  0.8333333 -0.5  0.8333333
[3,] 0    0    1    0     0.5 -0.8333333  0.5  0.1666667
[4,] 0    0    0    1     0.5 -0.1666667 -0.5 -0.1666667

Por tanto, la inversa es la submatriz formada por las últimas cuatro columnas. 

In [40]:
rAI[,5:8]

[,1] [,2]       [,3] [,4]      
[1,] -0.5  0.5000000  0.5 -0.5000000
[2,] -0.5  0.8333333 -0.5  0.8333333
[3,]  0.5 -0.8333333  0.5  0.1666667
[4,]  0.5 -0.1666667 -0.5 -0.1666667

### Ejercicio

*Estudiar si la matriz*
$$
 \left(\begin{array}{rrrr}
 1 &  2 &  3 & 4 \\
 0 &  1 &   2 &  3 \\
 1 &  0 &  2  &  0 \\
 1 & 1 & 1 & 1
 \end{array}\right)
$$
*es regular y en tal caso, calcular su matriz inversa.*

In [41]:
A<-rbind(c(1,2,3,4),c(0,1,2,3),c(1,0,2,0),c(1,1,1,1))

In [42]:
solve(A)

ERROR: Error in solve.default(A): Lapack routine dgesv: system is exactly singular: U[4,4] = 0


Luego no tiene inversa. 

In [43]:
Rank(A)

[1] 3

In [44]:
rref(cbind(A,diag(4)))

[,1] [,2] [,3] [,4]       [,5] [,6]       [,7]       [,8]      
[1,] 1    0    0    -1.3333333 0    -0.6666667  0.3333333  0.6666667
[2,] 0    1    0     1.6666667 0     0.3333333 -0.6666667  0.6666667
[3,] 0    0    1     0.6666667 0     0.3333333  0.3333333 -0.3333333
[4,] 0    0    0     0.0000000 1    -1.0000000  0.0000000 -1.0000000

La última fila muestra que la matriz no puede tener inversa.

## Matriz de paso entre dos matrices equivalentes por filas

### Ejercicio

*Estudiar si las matrices:*
$$
A=
 \left(\begin{array}{rrrr}
  1 &  1 & 1 & 1 \\
  0 &  1 & 1 & 1 \\
  0 &  0 & 1 & 1 \\
 \end{array}\right)
 ; \;\;
B=
 \left(\begin{array}{rrrr}
  1 & 0 &  0 &  0 \\
  1 & 1 &  0 &  0 \\
  1 & 1 &  1 &  1 \\
 \end{array}\right)
$$
*son equivalentes por filas, y en tal caso determinar una matriz regular $Q$ de forma que $A=Q\cdot B$.*

In [45]:
A<-matrix(c(1,1,1,1,0,1,1,1,0,0,1,1),3,4,byrow=TRUE)
A

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 0    1    1    1   
[3,] 0    0    1    1

In [46]:
B<-rbind(c(1,0,0,0),c(1,1,0,0),c(1,1,1,1))

Veamos cómo son sus formas normales de Hermite por filas.

In [47]:
rref(A)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    1

In [48]:
rref(B)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    1

Ahora calculemos la matriz $Q$ del enunciado. Para ello buscamos las matrices $Q_A$ y $Q_B$ tales que $Q_A A$ y $Q_B B$ estén en forma normal reducida por filas.

In [49]:
rAI<-rref(cbind(A,diag(3)))
rAI

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0    0    0    1    -1    0  
[2,] 0    1    0    0    0     1   -1  
[3,] 0    0    1    1    0     0    1

In [50]:
QA<-rAI[,-(1:4)]
QA

[,1] [,2] [,3]
[1,] 1    -1    0  
[2,] 0     1   -1  
[3,] 0     0    1

In [51]:
QB<-rref(cbind(B,diag(3)))[,-(1:4)]

Sabemos que $Q_A A = Q_B B$, por lo que la matriz $Q$ que buscamos es $Q_A^{-1}Q_B$.

In [52]:
Q<-solve(QA)%*%QB

In [53]:
Q

[,1] [,2] [,3]
[1,]  0    0   1   
[2,] -1    0   1   
[3,]  0   -1   1

Finalmente, comprobamos que $QB$ es $A$.

In [54]:
Q%*%B

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 0    1    1    1   
[3,] 0    0    1    1

## Determinantes y operaciones elementales

### Ejercicio

*Calcular el determinante*
$$
\left|
\begin{array}{rrrr}
1 & 1/2 & 1/3 & 1/5\\
-1 & 1/2 & -1/3 & -1/5\\
1 & 1/2 & 4/3 & 1/5\\
2 & 1 & 2/3 & 11/5\\
\end{array}
\right|.
$$

In [55]:
A<-rbind(c(1,1/2,1/3,1/5),c(-1,1/2,-1/3,-1/5),c(1,1/2,4/3,1/5),c(2,1,2/3,11/5))

En `R` podemos utilizar `det` para calcular el determinante de una matriz.

In [56]:
det(A)

[1] 1.8

Hagamos operaciones elementales por filas que no alteren el determinante de forma que lleguemos a una matriz triangular.

In [57]:
A

[,1] [,2] [,3]       [,4]
[1,]  1   0.5   0.3333333  0.2
[2,] -1   0.5  -0.3333333 -0.2
[3,]  1   0.5   1.3333333  0.2
[4,]  2   1.0   0.6666667  2.2

Vamos a conseguir ceros debajo de la primera posición de la primera fila. Para ello empezamos cambiando la segunda fila por la suma de las dos primeras files (lo que no altera el valor del determinante).

In [58]:
A[2,]<-A[1,]+A[2,]
A

[,1] [,2] [,3]      [,4]
[1,] 1    0.5  0.3333333 0.2 
[2,] 0    1.0  0.0000000 0.0 
[3,] 1    0.5  1.3333333 0.2 
[4,] 2    1.0  0.6666667 2.2

Ahor cambiamos la tercera por la diferencia de la tercera con la primera.

In [59]:
A[3,]<-A[3,]-A[1,]
A

[,1] [,2] [,3]      [,4]
[1,] 1    0.5  0.3333333 0.2 
[2,] 0    1.0  0.0000000 0.0 
[3,] 0    0.0  1.0000000 0.0 
[4,] 2    1.0  0.6666667 2.2

Y la cuarta por la diferencia de la cuarta por dos veces la primera.

In [60]:
A[4,]<-A[4,]-2*A[1,]

In [61]:
A

[,1] [,2] [,3]      [,4]
[1,] 1    0.5  0.3333333 0.2 
[2,] 0    1.0  0.0000000 0.0 
[3,] 0    0.0  1.0000000 0.0 
[4,] 0    0.0  0.0000000 1.8

La matriz ya es triangular, con lo que el determinante es el producto de los elementos de la diagonal.

In [62]:
diag(A)

[1] 1.0 1.0 1.0 1.8

In [63]:
prod(diag(A))

[1] 1.8

### El paquete `fractional`

Por defecto `R` utiliza reales (dobles) para guardar las entradas de una matriz. El paquete `fractional` sirve para mostrar aproximaciones racionales de esos reales, aunque las operaciones sigan haciéndose con números reales.

In [6]:
library("fractional")

In [7]:
A<-fractional(cbind(rbind(c(3,2,3,4),c(3,2,2,3),c(2,1,2,1),c(0,1,1,0)),diag(4)))
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 3    2    3    4    1    0    0    0   
[2,] 3    2    2    3    0    1    0    0   
[3,] 2    1    2    1    0    0    1    0   
[4,] 0    1    1    0    0    0    0    1

Nótese que ahora el tipo de las entradas de `A` es `fractional`.

In [4]:
print(rref(A))

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1    .    .    . -1/2  1/2  1/2 -1/2
[2,]    .    1    .    . -1/2  5/6 -1/2  5/6
[3,]    .    .    1    .  1/2 -5/6  1/2  1/6
[4,]    .    .    .    1  1/2 -1/6 -1/2 -1/6


### Forma normal de Hermite con `matlib`

La librería `matlib` ofrece la posibilidad de mostrar las operaciones elementales que llevan a la forma normal de Hermite de una matriz. Veámoslo con el primer ejemplo que hicimos.

In [67]:
library("matlib")


Attaching package: ‘matlib’


The following objects are masked from ‘package:pracma’:

    angle, inv




In [68]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
echelon(A,verbose=TRUE)


Initial matrix:
     [,1] [,2] [,3] [,4]
[1,]   -2   -4    2    2
[2,]    3    6   -3   -3
[3,]    1    2    0    1

row: 1 

 exchange rows 1 and 2 
     [,1] [,2] [,3] [,4]
[1,]    3    6   -3   -3
[2,]   -2   -4    2    2
[3,]    1    2    0    1

 multiply row 1 by 0.3333333 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]   -2   -4    2    2
[3,]    1    2    0    1

 multiply row 1 by 2 and add to row 2 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    0    0
[3,]    1    2    0    1

 subtract row 1 from row 3 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    0    0
[3,]    0    0    1    2

row: 2 

 exchange rows 2 and 3 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    1    2
[3,]    0    0    0    0

 multiply row 2 by 1 and add to row 1 
     [,1] [,2] [,3] [,4]
[1,]    1    2    0    1
[2,]    0    0    1    2
[3,]    0    0    0    0

row: 3 


También se puede utilizar para calcular una forma que no sea reducida.

In [69]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
echelon(A,reduced=FALSE,verbose=TRUE)


Initial matrix:
     [,1] [,2] [,3] [,4]
[1,]   -2   -4    2    2
[2,]    3    6   -3   -3
[3,]    1    2    0    1

row: 1 

 exchange rows 1 and 2 
     [,1] [,2] [,3] [,4]
[1,]    3    6   -3   -3
[2,]   -2   -4    2    2
[3,]    1    2    0    1

 multiply row 1 by 0.3333333 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]   -2   -4    2    2
[3,]    1    2    0    1

 multiply row 1 by 2 and add to row 2 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    0    0
[3,]    1    2    0    1

 subtract row 1 from row 3 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    0    0
[3,]    0    0    1    2

row: 2 

 exchange rows 2 and 3 
     [,1] [,2] [,3] [,4]
[1,]    1    2   -1   -1
[2,]    0    0    1    2
[3,]    0    0    0    0

row: 3 


También podemos hacer que las operaciones entre racionales se muestren sin usar notación decimal. Veamos uno de los ejemplos que hicimos de cálculo de inversa de una matriz.

In [70]:
A<-rbind(c(3,2,3,4),c(3,2,2,3),c(2,1,2,1),c(0,1,1,0))
echelon(cbind(A,diag(4)),verbose=TRUE,fractions=TRUE)


Initial matrix:
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 3    2    3    4    1    0    0    0   
[2,] 3    2    2    3    0    1    0    0   
[3,] 2    1    2    1    0    0    1    0   
[4,] 0    1    1    0    0    0    0    1   

row: 1 

 multiply row 1 by 1/3 
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]   1  2/3    1  4/3  1/3    0    0    0 
[2,]   3    2    2    3    0    1    0    0 
[3,]   2    1    2    1    0    0    1    0 
[4,]   0    1    1    0    0    0    0    1 

 multiply row 1 by 3 and subtract from row 2 
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]   1  2/3    1  4/3  1/3    0    0    0 
[2,]   0    0   -1   -1   -1    1    0    0 
[3,]   2    1    2    1    0    0    1    0 
[4,]   0    1    1    0    0    0    0    1 

 multiply row 1 by 2 and subtract from row 3 
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1  2/3    1  4/3  1/3    0    0    0
[2,]    0    0   -1   -1   -1    1    0    0
[3,]    0 -1/3    0 -5/3 -2/3    0    1    0


O que nos muestre los resultados en `LaTeX`.

In [71]:
A<-rbind(c(-2,-4,2,2),c(3,6,-3,-3),c(1,2,0,1))
echelon(A,reduced=FALSE,verbose=TRUE,latex=TRUE,fractions=TRUE)


Initial matrix:
\left[
 \begin{array}{llll}
  -2 & -4 & 2 & 2 \\ 
  3 & 6 & -3 & -3 \\ 
  1 & 2 & 0 & 1 \\ 
  \end{array}
\right]

row: 1 

 exchange rows 1 and 2 
\left[
 \begin{array}{llll}
  3 & 6 & -3 & -3 \\ 
  -2 & -4 & 2 & 2 \\ 
  1 & 2 & 0 & 1 \\ 
  \end{array}
\right]

 multiply row 1 by 1/3 
\left[
 \begin{array}{llll}
  1 & 2 & -1 & -1 \\ 
  -2 & -4 & 2 & 2 \\ 
  1 & 2 & 0 & 1 \\ 
  \end{array}
\right]

 multiply row 1 by 2 and add to row 2 
\left[
 \begin{array}{llll}
  1 & 2 & -1 & -1 \\ 
  0 & 0 & 0 & 0 \\ 
  1 & 2 & 0 & 1 \\ 
  \end{array}
\right]

 subtract row 1 from row 3 
\left[
 \begin{array}{llll}
  1 & 2 & -1 & -1 \\ 
  0 & 0 & 0 & 0 \\ 
  0 & 0 & 1 & 2 \\ 
  \end{array}
\right]

row: 2 

 exchange rows 2 and 3 
\left[
 \begin{array}{llll}
  1 & 2 & -1 & -1 \\ 
  0 & 0 & 1 & 2 \\ 
  0 & 0 & 0 & 0 \\ 
  \end{array}
\right]

row: 3 
